PHR afpacket integration
route-rs/route-rs pull request #219
Opened 2020-03-23 03:41 UTC by moosingin3space

2020-03-31 02:12 UTC, CollinValley commented
Nathan, can you rebase all your changes on top of the current PHR? That should resolve any issues before we merge this.

2020-03-31 04:47 UTC, moosingin3space commented
Rebased (and removed Drew's change as well).

2020-03-31 23:23 UTC, CollinValley requested changes
The code itself is in a good state. But we need doc comments on the parts that end users are expected to see, such as the links themselves.

2020-03-31 23:23 UTC, CollinValley commented on route-rs-afpacket/tests/integration_test.rs
> +#[ignore]
Leave a comment why this test can't be run by default, maybe with steps to run the test by hand.

2020-03-31 23:23 UTC, CollinValley commented on route-rs-afpacket/tests/integration_test.rs
> +#[ignore]
All the other ignored tests should follow the same pattern

2020-03-31 23:23 UTC, CollinValley commented on route-rs-afpacket/src/output.rs
> +pub struct AfPacketOutputLink {
Need documentation before we merge. 
Please describe what this link is, and how it is useful.

2020-03-31 23:23 UTC, CollinValley commented on route-rs-afpacket/src/input.rs
> +pub struct AfPacketInputLink {
Need documentation before we merge. 
Please describe what this link is, and how it is useful.

2020-03-31 23:24 UTC, CollinValley commented on route-rs-afpacket/src/output.rs
> +pub struct AfPacketOutputLink {
Nit: Remove Link from the name,  accidental Hungarian.

2020-04-02 02:56 UTC, moosingin3space commented on afpacket/src/sockets.rs
> -impl Read for BoundSocket {
Write down why I did this.

2020-04-02 02:58 UTC, moosingin3space commented on afpacket/src/tokio_sockets.rs
> +    pub fn split(self) -> (SendHalf, RecvHalf) {
Clarify where this came from (`tokio::split`)

2020-04-02 03:14 UTC, moosingin3space commented on afpacket/src/tokio_sockets.rs
> +    pub fn poll_lock_tx<'a>(
Expand this -- "reserving a space in the transmit queue"

2020-04-02 03:16 UTC, moosingin3space commented on afpacket/src/tokio_sockets.rs
> +unsafe impl Sync for SendHalf {}
Note why these are safe (because `Guard`).

2020-04-02 03:20 UTC, moosingin3space commented on afpacket/src/tokio_sockets.rs
> +        // this is safe because the Inner is stored in an Arc
Expand

2020-04-02 03:22 UTC, moosingin3space commented on route-rs-afpacket/src/input.rs
> +const MTU: usize = 1500;
This should almost certainly be configurable.

2020-04-02 03:30 UTC, moosingin3space commented on route-rs-afpacket/src/output.rs
> +            let mut lock =
Needs to be outside the loop.

2020-04-02 03:30 UTC, moosingin3space commented on route-rs-afpacket/src/output.rs
> +                ready!(me.egress.poll_lock_tx(cx)).expect("AfPacketOutputLink: failed to write");
Clarify error message.

2020-05-11 18:43 UTC, CollinValley approved these changes
LGTMMD

2020-05-26 19:24 UTC, merged